
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 35;
  public static final int MULT = 16;
  public static final int GE = 25;
  public static final int DOUBLE = 9;
  public static final int LPAREN = 31;
  public static final int INT = 7;
  public static final int FOR = 5;
  public static final int MINUS = 15;
  public static final int RPAREN = 32;
  public static final int NOT = 28;
  public static final int SEMICOLON = 29;
  public static final int AND = 26;
  public static final int LT = 22;
  public static final int OR = 27;
  public static final int COMMA = 30;
  public static final int DIV = 17;
  public static final int PLUS = 14;
  public static final int ASSIGN = 19;
  public static final int MAIN = 11;
  public static final int IF = 2;
  public static final int LE = 23;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int RBRACKET = 36;
  public static final int TRUE = 12;
  public static final int error = 1;
  public static final int MOD = 18;
  public static final int VOID = 10;
  public static final int EQ = 20;
  public static final int LBRACE = 33;
  public static final int ELSE = 3;
  public static final int WHILE = 4;
  public static final int FLOAT = 8;
  public static final int RBRACE = 34;
  public static final int NE = 21;
  public static final int DOUBLE_LITERAL = 39;
  public static final int FLOAT_LITERAL = 38;
  public static final int FALSE = 13;
  public static final int GT = 24;
  public static final int IDENTIFIER = 40;
  public static final int INTEGER_LITERAL = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "INT",
  "FLOAT",
  "DOUBLE",
  "VOID",
  "MAIN",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "ASSIGN",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "SEMICOLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "DOUBLE_LITERAL",
  "IDENTIFIER"
  };
}

